export enum categoryEnum {
  New = "New",
  Strains = "Strains",
  Edibles = "Edibles",
  PreRoll = "PreRoll",
  Concentrates = "Concentrates",
  BarMenu = "Bar Menu",
  CafeMenu = "Cafe Menu",
  DabBar = "Dab Bar",
  Cartridges = "Cartridges",
  Merch = "Merch",
  Infused = "Infused",
  WineDown = "Wine Down",
  HHBeer = "HH Beer",
  HappyHourMixDrinks = "Happy Hour Mix Drinks",
}
